// LLM Provider Configuration
export interface LLMProvider {
  id: string
  name: string
  description: string
  website: string
  category: "free" | "freemium" | "paid"
  features: string[]
  models: LLMModel[]
  authType: "api_key" | "oauth" | "none"
  apiKeyName?: string
  baseUrl?: string
  docsUrl: string
  freeLimit?: string
  icon: string
}

export interface LLMModel {
  id: string
  name: string
  description: string
  contextWindow: number
  inputCost?: number // per 1M tokens
  outputCost?: number // per 1M tokens
  free: boolean
  capabilities: ("text" | "vision" | "code" | "function_calling" | "research")[]
}

export const LLM_PROVIDERS: LLMProvider[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    description: "Unified API for 300+ models from 60+ providers, including 25+ free models",
    website: "https://openrouter.ai",
    category: "freemium",
    features: ["25+ free models", "Unified API", "Model fallback", "No rate limits on paid"],
    freeLimit: "50 requests/day on free tier",
    authType: "api_key",
    apiKeyName: "OPENROUTER_API_KEY",
    baseUrl: "https://openrouter.ai/api/v1",
    docsUrl: "https://openrouter.ai/docs",
    icon: "openrouter",
    models: [
      {
        id: "meta-llama/llama-3.3-70b-instruct:free",
        name: "Llama 3.3 70B (Free)",
        description: "Meta's latest open-source model, great for general tasks",
        contextWindow: 131072,
        free: true,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "google/gemini-2.0-flash-exp:free",
        name: "Gemini 2.0 Flash (Free)",
        description: "Google's fast multimodal model",
        contextWindow: 1048576,
        free: true,
        capabilities: ["text", "vision", "code"],
      },
      {
        id: "deepseek/deepseek-r1:free",
        name: "DeepSeek R1 (Free)",
        description: "Advanced reasoning model with chain-of-thought",
        contextWindow: 65536,
        free: true,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "qwen/qwen-2.5-72b-instruct:free",
        name: "Qwen 2.5 72B (Free)",
        description: "Alibaba's powerful open model",
        contextWindow: 32768,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "mistralai/mistral-small-3.1-24b-instruct:free",
        name: "Mistral Small 3.1 (Free)",
        description: "Fast and efficient for everyday tasks",
        contextWindow: 96000,
        free: true,
        capabilities: ["text", "code", "function_calling"],
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    description: "Ultra-fast LLM inference with free tier - fastest in the world",
    website: "https://groq.com",
    category: "freemium",
    features: ["Fastest inference", "Free tier", "Open models", "Low latency"],
    freeLimit: "14,400 requests/day, 30 req/min",
    authType: "api_key",
    apiKeyName: "GROQ_API_KEY",
    baseUrl: "https://api.groq.com/openai/v1",
    docsUrl: "https://console.groq.com/docs",
    icon: "groq",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        description: "Best for complex tasks requiring reasoning",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        description: "Fastest option for simple tasks",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        description: "Excellent for code and technical content",
        contextWindow: 32768,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "gemma2-9b-it",
        name: "Gemma 2 9B",
        description: "Google's efficient open model",
        contextWindow: 8192,
        free: true,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    description: "Run open-source models with competitive pricing and free credits",
    website: "https://together.ai",
    category: "freemium",
    features: ["$25 free credits", "100+ models", "Fine-tuning", "Embeddings"],
    freeLimit: "$25 free credits on signup",
    authType: "api_key",
    apiKeyName: "TOGETHER_API_KEY",
    baseUrl: "https://api.together.xyz/v1",
    docsUrl: "https://docs.together.ai",
    icon: "together",
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        description: "Optimized for speed and quality",
        contextWindow: 131072,
        inputCost: 0.88,
        outputCost: 0.88,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        description: "Advanced reasoning with thinking tokens",
        contextWindow: 65536,
        inputCost: 3.0,
        outputCost: 7.0,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "Qwen/QwQ-32B-Preview",
        name: "QwQ 32B Preview",
        description: "Alibaba's reasoning model",
        contextWindow: 32768,
        inputCost: 1.2,
        outputCost: 1.2,
        free: false,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Access thousands of open-source models via Inference API",
    website: "https://huggingface.co",
    category: "freemium",
    features: ["1000+ models", "Free tier", "Model hub", "Spaces"],
    freeLimit: "Rate-limited free tier",
    authType: "api_key",
    apiKeyName: "HUGGINGFACE_API_KEY",
    baseUrl: "https://api-inference.huggingface.co",
    docsUrl: "https://huggingface.co/docs/api-inference",
    icon: "huggingface",
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B Instruct",
        description: "Meta's flagship open model",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "mistralai/Mistral-7B-Instruct-v0.3",
        name: "Mistral 7B Instruct",
        description: "Fast and efficient",
        contextWindow: 32768,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "HuggingFaceH4/zephyr-7b-beta",
        name: "Zephyr 7B",
        description: "Fine-tuned for helpfulness",
        contextWindow: 8192,
        free: true,
        capabilities: ["text"],
      },
    ],
  },
  {
    id: "ollama",
    name: "Ollama (Self-Hosted)",
    description: "Run LLMs locally on your own hardware - completely free",
    website: "https://ollama.ai",
    category: "free",
    features: ["100% free", "Privacy focused", "No rate limits", "Local inference"],
    freeLimit: "Unlimited (self-hosted)",
    authType: "none",
    baseUrl: "http://localhost:11434/api",
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    icon: "ollama",
    models: [
      {
        id: "llama3.3:70b",
        name: "Llama 3.3 70B",
        description: "Requires 40GB+ VRAM",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "llama3.2:3b",
        name: "Llama 3.2 3B",
        description: "Light model, runs on most hardware",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "deepseek-r1:7b",
        name: "DeepSeek R1 7B",
        description: "Reasoning model, 8GB VRAM",
        contextWindow: 65536,
        free: true,
        capabilities: ["text", "code"],
      },
      {
        id: "qwen2.5:7b",
        name: "Qwen 2.5 7B",
        description: "Balanced performance",
        contextWindow: 32768,
        free: true,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "stanford-storm",
    name: "Stanford STORM",
    description: "Research-powered article generation - creates Wikipedia-style reports",
    website: "https://storm.genie.stanford.edu",
    category: "free",
    features: ["Research synthesis", "Wikipedia-style articles", "Multi-source", "Citations"],
    freeLimit: "Research preview - free",
    authType: "none",
    docsUrl: "https://github.com/stanford-oval/storm",
    icon: "stanford",
    models: [
      {
        id: "storm-article",
        name: "STORM Article Generator",
        description: "Generate comprehensive research articles from a topic",
        contextWindow: 0,
        free: true,
        capabilities: ["research", "text"],
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "AI-powered search and research with real-time information",
    website: "https://perplexity.ai",
    category: "freemium",
    features: ["Real-time search", "Citations", "Research", "Reasoning"],
    freeLimit: "Limited free searches",
    authType: "api_key",
    apiKeyName: "PERPLEXITY_API_KEY",
    baseUrl: "https://api.perplexity.ai",
    docsUrl: "https://docs.perplexity.ai",
    icon: "perplexity",
    models: [
      {
        id: "llama-3.1-sonar-small-128k-online",
        name: "Sonar Small (Online)",
        description: "Fast search-augmented responses",
        contextWindow: 128000,
        inputCost: 0.2,
        outputCost: 0.2,
        free: false,
        capabilities: ["text", "research"],
      },
      {
        id: "llama-3.1-sonar-large-128k-online",
        name: "Sonar Large (Online)",
        description: "More thorough research",
        contextWindow: 128000,
        inputCost: 1.0,
        outputCost: 1.0,
        free: false,
        capabilities: ["text", "research"],
      },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    description: "Fast inference for open models with competitive pricing",
    website: "https://fireworks.ai",
    category: "freemium",
    features: ["Fast inference", "Function calling", "JSON mode", "Fine-tuning"],
    freeLimit: "$1 free credits",
    authType: "api_key",
    apiKeyName: "FIREWORKS_API_KEY",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    docsUrl: "https://docs.fireworks.ai",
    icon: "fireworks",
    models: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        name: "Llama 3.3 70B",
        description: "High quality, fast inference",
        contextWindow: 128000,
        inputCost: 0.9,
        outputCost: 0.9,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "accounts/fireworks/models/deepseek-r1",
        name: "DeepSeek R1",
        description: "Reasoning model",
        contextWindow: 65536,
        inputCost: 3.0,
        outputCost: 8.0,
        free: false,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "State-of-the-art reasoning models at low cost",
    website: "https://deepseek.com",
    category: "freemium",
    features: ["Advanced reasoning", "Chain-of-thought", "Very low cost", "Long context"],
    freeLimit: "Free tier available",
    authType: "api_key",
    apiKeyName: "DEEPSEEK_API_KEY",
    baseUrl: "https://api.deepseek.com/v1",
    docsUrl: "https://platform.deepseek.com/docs",
    icon: "deepseek",
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        description: "General purpose, very affordable",
        contextWindow: 65536,
        inputCost: 0.14,
        outputCost: 0.28,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner (R1)",
        description: "Advanced reasoning with thinking tokens",
        contextWindow: 65536,
        inputCost: 0.55,
        outputCost: 2.19,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    description: "Enterprise AI with strong retrieval and RAG capabilities",
    website: "https://cohere.com",
    category: "freemium",
    features: ["RAG optimized", "Embeddings", "Rerank", "Multi-lingual"],
    freeLimit: "1000 calls/month free",
    authType: "api_key",
    apiKeyName: "COHERE_API_KEY",
    baseUrl: "https://api.cohere.ai/v1",
    docsUrl: "https://docs.cohere.com",
    icon: "cohere",
    models: [
      {
        id: "command-r-plus",
        name: "Command R+",
        description: "Best for complex RAG tasks",
        contextWindow: 128000,
        inputCost: 2.5,
        outputCost: 10.0,
        free: false,
        capabilities: ["text", "research", "function_calling"],
      },
      {
        id: "command-r",
        name: "Command R",
        description: "Fast and efficient",
        contextWindow: 128000,
        inputCost: 0.15,
        outputCost: 0.6,
        free: false,
        capabilities: ["text", "research"],
      },
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    description: "World's fastest AI inference - 20x faster than GPUs",
    website: "https://cerebras.ai",
    category: "freemium",
    features: ["Fastest inference", "Llama models", "Free tier", "Low latency"],
    freeLimit: "Free tier available",
    authType: "api_key",
    apiKeyName: "CEREBRAS_API_KEY",
    baseUrl: "https://api.cerebras.ai/v1",
    docsUrl: "https://docs.cerebras.ai",
    icon: "cerebras",
    models: [
      {
        id: "llama3.3-70b",
        name: "Llama 3.3 70B",
        description: "Ultra-fast inference",
        contextWindow: 128000,
        inputCost: 0.85,
        outputCost: 1.2,
        free: false,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    description: "European AI leader with efficient open models",
    website: "https://mistral.ai",
    category: "freemium",
    features: ["European", "Efficient models", "Function calling", "Fine-tuning"],
    freeLimit: "Free tier for small models",
    authType: "api_key",
    apiKeyName: "MISTRAL_API_KEY",
    baseUrl: "https://api.mistral.ai/v1",
    docsUrl: "https://docs.mistral.ai",
    icon: "mistral",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        description: "Most capable Mistral model",
        contextWindow: 128000,
        inputCost: 2.0,
        outputCost: 6.0,
        free: false,
        capabilities: ["text", "code", "function_calling", "vision"],
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        description: "Cost-effective for simple tasks",
        contextWindow: 32000,
        inputCost: 0.2,
        outputCost: 0.6,
        free: false,
        capabilities: ["text", "code", "function_calling"],
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        description: "Optimized for code generation",
        contextWindow: 32000,
        inputCost: 0.2,
        outputCost: 0.6,
        free: false,
        capabilities: ["code", "function_calling"],
      },
    ],
  },
  {
    id: "lmstudio",
    name: "LM Studio (Local)",
    description: "Run models locally with a beautiful GUI - completely free",
    website: "https://lmstudio.ai",
    category: "free",
    features: ["100% free", "GUI interface", "GGUF models", "Privacy focused"],
    freeLimit: "Unlimited (self-hosted)",
    authType: "none",
    baseUrl: "http://localhost:1234/v1",
    docsUrl: "https://lmstudio.ai/docs",
    icon: "lmstudio",
    models: [
      {
        id: "local-model",
        name: "Any GGUF Model",
        description: "Run any model from Hugging Face",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
    ],
  },
  {
    id: "llamacpp",
    name: "llama.cpp Server",
    description: "High-performance local inference server",
    website: "https://github.com/ggerganov/llama.cpp",
    category: "free",
    features: ["100% free", "CPU/GPU", "Quantization", "Server mode"],
    freeLimit: "Unlimited (self-hosted)",
    authType: "none",
    baseUrl: "http://localhost:8080/v1",
    docsUrl: "https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md",
    icon: "llamacpp",
    models: [
      {
        id: "local-gguf",
        name: "Any GGUF Model",
        description: "High performance local inference",
        contextWindow: 128000,
        free: true,
        capabilities: ["text", "code"],
      },
    ],
  },
]

// Provider icons mapping
export const PROVIDER_ICONS: Record<string, string> = {
  openrouter: "https://openrouter.ai/favicon.ico",
  groq: "https://groq.com/favicon.ico",
  together: "https://together.ai/favicon.ico",
  huggingface: "https://huggingface.co/favicon.ico",
  ollama: "https://ollama.ai/public/ollama.png",
  stanford: "https://stanford.edu/favicon.ico",
  perplexity: "https://perplexity.ai/favicon.ico",
  fireworks: "https://fireworks.ai/favicon.ico",
  deepseek: "https://deepseek.com/favicon.ico",
  cohere: "https://cohere.com/favicon.ico",
  cerebras: "https://cerebras.ai/favicon.ico",
  mistral: "https://mistral.ai/favicon.ico",
  lmstudio: "https://lmstudio.ai/favicon.ico",
  llamacpp: "https://github.com/ggerganov/llama.cpp/raw/master/media/llama.png",
}

// Get all free models across providers
export function getFreeModels(): { provider: LLMProvider; model: LLMModel }[] {
  const freeModels: { provider: LLMProvider; model: LLMModel }[] = []
  
  for (const provider of LLM_PROVIDERS) {
    for (const model of provider.models) {
      if (model.free) {
        freeModels.push({ provider, model })
      }
    }
  }
  
  return freeModels
}

// Get providers by category
export function getProvidersByCategory(category: LLMProvider["category"]): LLMProvider[] {
  return LLM_PROVIDERS.filter(p => p.category === category)
}
